version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80
  
  product-service2:
    build: ./product2
    volumes:
      - ./product2:/usr/src/app
    ports:
      - 5002:80

